version: 0.0
os: linux
files:
  - source: target/AWS-CodePipeline-POC.war
    destination: /opt/awscodepipeline
  - source: service.sh
    destination: /opt/awscodepipeline

hooks:
  ApplicationStart:
    - location: restart.sh
      timeout: 180
