version: 0.0
os: linux
files:
  - source: target/AWS-CodePipeline-POC.war
    destination: /opt/awscodepipeline

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 180
  ApplicationStart:
    - location: run.sh
      timeout: 180
